cc_library(
    name = "x",
    srcs = ["x.cc"],
    hdrs = ["x.h"],
)

cc_library(
    name = "hello",
    srcs = ["hello.cpp"],
    hdrs = ["hello.h],

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        ":x"
        ":hello"
    ],   
)
